[functions.invite-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.punch]
verify_jwt = false

[functions.auto-punch-out]
verify_jwt = false

[functions.mark-absent]
verify_jwt = false

[functions.send-scheduled-notifications]
verify_jwt = false

[functions.send-test-notification]
verify_jwt = false

[functions.notify]
verify_jwt = false
