import type { TodayRecord } from '@/lib/services/attendance.service';

/** Matches doc §24 / TodayStatusCard tests — Tue 2025-06-10 scenarios use this shift. */
export const multiSessionDefaultShift = {
  workStartTime: '09:00',
  workEndTime: '18:00',
  gracePeriodMinutes: 15,
  bufferMinutesAfterShift: 5,
  weeklyOffDays: [5, 6] as number[],
  minimumRequiredMinutes: null as number | null,
};

/** §24.1a: S1 closed, S2 open; aggregate `log` still has S1’s check_out_time. */
export function todayRecord24_1a(): TodayRecord {
  return {
    log: {
      id: 'pseudo-two',
      org_id: 'o1',
      user_id: 'u1',
      date: '2025-06-10',
      check_in_time: '08:30',
      check_out_time: '12:00',
      check_in_lat: null,
      check_in_lng: null,
      check_out_lat: null,
      check_out_lng: null,
      status: 'present',
      is_dev: false,
      auto_punch_out: false,
    },
    punches: [],
    shift: { ...multiSessionDefaultShift },
    sessions: [
      {
        id: 's1',
        org_id: 'o1',
        user_id: 'u1',
        date: '2025-06-10',
        check_in_time: '08:30',
        check_out_time: '12:00',
        status: 'present',
        is_overtime: false,
        is_auto_punch_out: false,
        is_early_departure: false,
        needs_review: false,
        duration_minutes: 210,
        last_action_at: '2025-06-10T12:00:00Z',
        is_dev: false,
        created_at: '2025-06-10T08:30:00Z',
        updated_at: '2025-06-10T12:00:00Z',
      },
      {
        id: 's2',
        org_id: 'o1',
        user_id: 'u1',
        date: '2025-06-10',
        check_in_time: '13:00',
        check_out_time: null,
        status: 'present',
        is_overtime: false,
        is_auto_punch_out: false,
        is_early_departure: false,
        needs_review: false,
        duration_minutes: 0,
        last_action_at: '2025-06-10T13:00:00Z',
        is_dev: false,
        created_at: '2025-06-10T13:00:00Z',
        updated_at: '2025-06-10T13:00:00Z',
      },
    ],
  };
}

/** §24.1: S1/S2 closed, S3 open; aggregate `log` check_out_time from S2. */
export function todayRecord24_1(): TodayRecord {
  return {
    log: {
      id: 'pseudo-summary',
      org_id: 'o1',
      user_id: 'u1',
      date: '2025-06-10',
      check_in_time: '08:30',
      check_out_time: '14:00',
      check_in_lat: null,
      check_in_lng: null,
      check_out_lat: null,
      check_out_lng: null,
      status: 'present',
      is_dev: false,
      auto_punch_out: false,
    },
    punches: [],
    shift: { ...multiSessionDefaultShift },
    sessions: [
      {
        id: 's1',
        org_id: 'o1',
        user_id: 'u1',
        date: '2025-06-10',
        check_in_time: '08:30',
        check_out_time: '12:00',
        status: 'present',
        is_overtime: false,
        is_auto_punch_out: false,
        is_early_departure: false,
        needs_review: false,
        duration_minutes: 210,
        last_action_at: '2025-06-10T12:00:00Z',
        is_dev: false,
        created_at: '2025-06-10T08:30:00Z',
        updated_at: '2025-06-10T12:00:00Z',
      },
      {
        id: 's2',
        org_id: 'o1',
        user_id: 'u1',
        date: '2025-06-10',
        check_in_time: '13:00',
        check_out_time: '14:00',
        status: 'present',
        is_overtime: false,
        is_auto_punch_out: false,
        is_early_departure: false,
        needs_review: false,
        duration_minutes: 60,
        last_action_at: '2025-06-10T14:00:00Z',
        is_dev: false,
        created_at: '2025-06-10T13:00:00Z',
        updated_at: '2025-06-10T14:00:00Z',
      },
      {
        id: 's3',
        org_id: 'o1',
        user_id: 'u1',
        date: '2025-06-10',
        check_in_time: '14:30',
        check_out_time: null,
        status: 'present',
        is_overtime: false,
        is_auto_punch_out: false,
        is_early_departure: false,
        needs_review: false,
        duration_minutes: 0,
        last_action_at: '2025-06-10T14:30:00Z',
        is_dev: false,
        created_at: '2025-06-10T14:30:00Z',
        updated_at: '2025-06-10T14:30:00Z',
      },
    ],
  };
}
