import type { TodayRecord } from '@/lib/services/attendance.service';

/** Matches doc §24 / TodayStatusCard tests — Tue 2025-06-10 scenarios use this shift. */
export const multiSessionDefaultShift = {
  workStartTime: '09:00',
  workEndTime: '18:00',
  gracePeriodMinutes: 15,
  bufferMinutesAfterShift: 5,
  minimumOvertimeMinutes: 30,
  weeklyOffDays: [5, 6] as number[],
  minimumRequiredMinutes: null as number | null,
};

/** §24.1a: S1 closed, S2 open; summary keeps the aggregate first/last times. */
export function todayRecord24_1a(): TodayRecord {
  return {
    punches: [],
    shift: { ...multiSessionDefaultShift },
    summary: {
      id: 'pseudo-two',
      org_id: 'o1',
      user_id: 'u1',
      date: '2025-06-10',
      first_check_in: '08:30',
      last_check_out: '12:00',
      total_work_minutes: 210,
      total_overtime_minutes: 0,
      effective_status: 'present',
      has_overtime: false,
      is_incomplete_shift: false,
      session_count: 2,
      updated_at: '2025-06-10T13:00:00Z',
    },
    sessions: [
      {
        id: 's1',
        org_id: 'o1',
        user_id: 'u1',
        date: '2025-06-10',
        check_in_time: '08:30',
        check_out_time: '12:00',
        status: 'present',
        is_overtime: false,
        is_auto_punch_out: false,
        is_early_departure: false,
        needs_review: false,
        duration_minutes: 210,
        last_action_at: '2025-06-10T12:00:00Z',
        is_dev: false,
        created_at: '2025-06-10T08:30:00Z',
        updated_at: '2025-06-10T12:00:00Z',
      },
      {
        id: 's2',
        org_id: 'o1',
        user_id: 'u1',
        date: '2025-06-10',
        check_in_time: '13:00',
        check_out_time: null,
        status: 'present',
        is_overtime: false,
        is_auto_punch_out: false,
        is_early_departure: false,
        needs_review: false,
        duration_minutes: 0,
        last_action_at: '2025-06-10T13:00:00Z',
        is_dev: false,
        created_at: '2025-06-10T13:00:00Z',
        updated_at: '2025-06-10T13:00:00Z',
      },
    ],
  };
}

/** §24.1: S1/S2 closed, S3 open; summary carries the aggregate first/last times from closed segments. */
export function todayRecord24_1(): TodayRecord {
  return {
    punches: [],
    shift: { ...multiSessionDefaultShift },
    summary: {
      id: 'pseudo-summary',
      org_id: 'o1',
      user_id: 'u1',
      date: '2025-06-10',
      first_check_in: '08:30',
      last_check_out: '14:00',
      total_work_minutes: 270,
      total_overtime_minutes: 0,
      effective_status: 'present',
      has_overtime: false,
      is_incomplete_shift: false,
      session_count: 3,
      updated_at: '2025-06-10T14:30:00Z',
    },
    sessions: [
      {
        id: 's1',
        org_id: 'o1',
        user_id: 'u1',
        date: '2025-06-10',
        check_in_time: '08:30',
        check_out_time: '12:00',
        status: 'present',
        is_overtime: false,
        is_auto_punch_out: false,
        is_early_departure: false,
        needs_review: false,
        duration_minutes: 210,
        last_action_at: '2025-06-10T12:00:00Z',
        is_dev: false,
        created_at: '2025-06-10T08:30:00Z',
        updated_at: '2025-06-10T12:00:00Z',
      },
      {
        id: 's2',
        org_id: 'o1',
        user_id: 'u1',
        date: '2025-06-10',
        check_in_time: '13:00',
        check_out_time: '14:00',
        status: 'present',
        is_overtime: false,
        is_auto_punch_out: false,
        is_early_departure: false,
        needs_review: false,
        duration_minutes: 60,
        last_action_at: '2025-06-10T14:00:00Z',
        is_dev: false,
        created_at: '2025-06-10T13:00:00Z',
        updated_at: '2025-06-10T14:00:00Z',
      },
      {
        id: 's3',
        org_id: 'o1',
        user_id: 'u1',
        date: '2025-06-10',
        check_in_time: '14:30',
        check_out_time: null,
        status: 'present',
        is_overtime: false,
        is_auto_punch_out: false,
        is_early_departure: false,
        needs_review: false,
        duration_minutes: 0,
        last_action_at: '2025-06-10T14:30:00Z',
        is_dev: false,
        created_at: '2025-06-10T14:30:00Z',
        updated_at: '2025-06-10T14:30:00Z',
      },
    ],
  };
}
